repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        -   id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

# todo: implement mypy type linting
#  - repo: local
#    hooks:
#      - id: type-linting
#        name: type-linting
#        entry: bash -c "pushd backend && make lint"
#        language: python
#        pass_filenames: false
