metrics:
  - name: mood
    user_prompt: "How do you feel right now?"
    emoji: true  # I'm not brave enough to put emojis in a YAML file
    baseline: 0
    values:
      ":zany_face:": 3
      ":grinning_face_with_smiling_eyes:": 2
      ":slightly_smiling_face:": 1
      ":face_without_mouth:": 0
      ":slightly_frowning_face:": -1
      ":frowning_face:": -2
      ":skull:": -3
  - name: sleep
    baseline: 8
    user_prompt: "How much sleep did you get today?"
    type: numeric
    values:
      lower_bound: 4
      upper_bound: 12

notifications:
  - text: "It's time to record your mood!"
    time: "18:00"

baseline:
  enabled: true
  auto: false
