services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mood-tracker:
    image: public.ecr.aws/c1o1h8f4/mood-tracker:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST="host.docker.internal:27017"
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    # volumes:
    #   - type: bind
    #     source: ./config.yaml
    #     target: /config.yaml
    depends_on:
      - mongodb

volumes:
  mongo_data:
