name: Build

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry
          poetry install --with dev

      - name: Run tests
        run: |
          make test

  create_infrastructure:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: eu-central-1

      - name: Create infrastructure
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

  build_docker:
    needs: create_infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/github-actions
          aws-region: us-east-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: 'public'
          mask-password: 'false'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry
          poetry export -f requirements.txt -o requirements.txt --without-hashes

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag public.ecr.aws/c1o1h8f4/mood-tracker:latest \
            --push .
            
